######################################################################
# Automatically generated by qmake (3.1) Tue Nov 21 11:50:06 2017
######################################################################

CONFIG-=qt
TEMPLATE = subdirs

# Directories
SUBDIRS = utilities unittest  
