######################################################################
# Automatically generated by qmake (3.1) Thu Jan 18 11:15:30 2018
######################################################################

TEMPLATE = lib
TARGET = utilities
INCLUDEPATH += .

# Input
HEADERS += textutils.h
SOURCES += textutils.cpp
